---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
- config/**/*
- tests/**/*
- database/migrations/*
- _ide_helper.php
- c3.php
