language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

branches:
  only:
    - master

sudo: false

install:
  - mysql -e 'create database stellardestiny;'
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - chmod -R 777 storage/
  - php artisan migrate
  - php artisan db:seed
  - php -S localhost:8000 -t public &
  - sleep 5 # give artisan serve some time to start
  - php vendor/bin/codecept build
  - cp tests/acceptance.suite.yml.ci tests/acceptance.suite.yml #copy over CI acceptance test configuration

script:
  - php vendor/bin/codecept run --report --coverage-xml

addons:
    code_climate:
        repo_token: 9dc9de1806a63d84f4ea92fa303e30cee43d1e12c7e25f61530b96e38b2c2564

after_script:
  - vendor/bin/test-reporter

after_failure:
  - cat storage/logs/laravel.log
  - cat tests/_output/*
