language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - APP_ENV=test
    - APP_DEBUG=false
    - APP_KEY=Tpk0wmVgmVvqMHIRGWgk1PTLvyCqs23e
    - DB_HOST=localhost
    - DB_DATABASE=stellardestiny
    - DB_USERNAME=root
    - DB_PASSWORD=
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

matrix:
  fast_finish: true

branches:
  only:
    - master

install:
  - mysql -e 'create database stellardestiny;'
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - chmod -R 777 storage/
  - php artisan migrate
  - php artisan db:seed
  - php -S localhost:8000 -t public &
  - sleep 5 # give artisan serve some time to start
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run --env travis --coverage-xml=build/logs/clover.xml

addons:
    code_climate:
        repo_token: 9dc9de1806a63d84f4ea92fa303e30cee43d1e12c7e25f61530b96e38b2c2564

after_script:
  - vendor/bin/test-reporter

after_failure:
  - cat storage/logs/laravel.log
  - cat tests/_output/*
