language: php

sudo: false

php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - APP_ENV=test
    - APP_DEBUG=false
    - APP_KEY=Tpk0wmVgmVvqMHIRGWgk1PTLvyCqs23e
    - DB_HOST=localhost
    - DB_DATABASE=stellardestiny
    - DB_USERNAME=root
    - DB_PASSWORD=
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
  - travis_retry composer self-update

install:
  - mysql -e 'create database stellardestiny;'
  - travis_retry composer install --prefer-source --no-interaction
  - chmod -R 777 storage/
  - php artisan migrate --seed
  - php artisan serve --quiet 2>&1 >/dev/null &
  - sleep 5
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run --env=travis

after_failure:
  - cat storage/logs/laravel.log
  - cat tests/_output/*

notifications:
  webhooks:
    urls:
      - http://stellardestiny.online/deploy
    on_success: always
    on_failure: never
    on_start: never
